In [4]:
#import libray yg dibutuhkan
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import random as rd

In [7]:
#import data ke sini dulu
data = pd.read_csv("datatrain.csv")
data.head()

Suhu  Waktu Kondisi Langit Kelembapan Terbang/Tidak
0  Normal  Siang        Berawan     Normal         Tidak
1  Normal  Siang          Cerah     Normal         Tidak
2  Normal   Pagi          Hujan     Normal         Tidak
3  Normal   Sore         Rintik     Rendah            Ya
4  Normal  Malam        Berawan     Tinggi         Tidak

In [8]:
#ubah data jadi biner
enc = OneHotEncoder(sparse=False)
datrain = enc.fit_transform(data).astype(int)
datrain = np.delete(datrain,14,1)
pd.DataFrame(datrain).head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   1   0   0   0   0   1   0   1   0   0   0   1   0   0   0
1   1   0   0   0   0   1   0   0   1   0   0   1   0   0   0
2   1   0   0   0   1   0   0   0   0   1   0   1   0   0   0
3   1   0   0   0   0   0   1   0   0   0   1   0   1   0   1
4   1   0   0   1   0   0   0   1   0   0   0   0   0   1   0

In [9]:
# generate populasi dulu dri data latih (train)
def generate_chromosome(n_population):
    population = []
    for i in range (n_population):
        n_kromsom = rd.randint(1,10)*15
        kromsom = rd.choices([0,1],k=n_kromsom) #1 gen
        population.append(np.array(kromsom))
    return population

In [10]:
# test generate chromsome
population = generate_chromosome(10)

In [11]:
def fitnessKromosom(kromsom,data_train):
    hitung = 0
    array_rule = np.split(kromsom,round(len(kromsom)/15))
    for data in data_train:
        kategoriData = np.split(data, [3,7,11,14])
        for rule in array_rule:
            kategoriRule = np.split(rule, [3,7,11,14])
            for i in range(5):
                if np.any(np.logical_and(kategoriData[i],kategoriRule[i]))==False:
                    break
            if i == 4:
                if(kategoriData[4] == kategoriRule[4]):
                    hitung += 1
                    break
                
    return hitung/80*100

In [12]:
def hitungfitness(populasi,data_train):
    fit = []
    for kromosom in populasi:
        fit.append(fitnessKromosom(kromosom,data_train))
    return fit

In [14]:
populasi = generate_chromosome(10)
fitness = hitungfitness(populasi,datrain)

In [20]:
populasi,fitness

([array([0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
         1, 0, 0, 1, 1, 1, 0, 1]),
  array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0]),
  array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
         1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
         0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0]),
  array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0]),
  array([1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
         0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
         0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
         0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
         0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
         1, 0, 0, 1, 1, 0, 1, 0, 0, 1]),
  array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
         0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
   

In [21]:
kromsom = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0])
fitnessKromosom(kromsom,datrain)

100.0

In [23]:
#seleksi ortu (turnamen selection)
def tournamentselection(populasi,fit):
    parent = []
    z = zip(populasi,fit)
    kandidat = random.sample(list(zip(populasi,fit)),random.randint(1,len(populasi)))
    kandidat = sorted(kandidat,key= lambda k:k[1],reverse=True)
    return kandidat[0][0]