In [15]:
#import libray yg dibutuhkan
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import random as rd

In [7]:
#import data ke sini dulu
data = pd.read_csv("datatrain.csv")
data.head()

Suhu  Waktu Kondisi Langit Kelembapan Terbang/Tidak
0  Normal  Siang        Berawan     Normal         Tidak
1  Normal  Siang          Cerah     Normal         Tidak
2  Normal   Pagi          Hujan     Normal         Tidak
3  Normal   Sore         Rintik     Rendah            Ya
4  Normal  Malam        Berawan     Tinggi         Tidak

In [10]:
#ubah data jadi biner
enc = OneHotEncoder(sparse=False)
datrain = enc.fit_transform(data).astype(int)
datrain = np.delete(datrain,14,1)
pd.DataFrame(datrain)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0    1   0   0   0   0   1   0   1   0   0   0   1   0   0   0
1    1   0   0   0   0   1   0   0   1   0   0   1   0   0   0
2    1   0   0   0   1   0   0   0   0   1   0   1   0   0   0
3    1   0   0   0   0   0   1   0   0   0   1   0   1   0   1
4    1   0   0   1   0   0   0   1   0   0   0   0   0   1   0
5    1   0   0   1   0   0   0   0   1   0   0   1   0   0   1
6    1   0   0   0   1   0   0   0   1   0   0   0   1   0   1
7    1   0   0   0   0   1   0   1   0   0   0   0   1   0   0
8    1   0   0   0   0   0   1   0   0   1   0   1   0   0   0
9    1   0   0   0   0   1   0   0   0   0   1   0   1   0   1
10   1   0   0   0   0   0   1   1   0   0   0   0   0   1   0
11   1   0   0   0   0   0   1   0   1   0   0   0   1   0   0
12   1   0   0   0   1   0   0   1   0   0   0   1   0   0   1
13   1   0   0   1   0   0   0   0   0   1   0   0   1   0   1
14   1   0   0   0   1   0   0   0   1   0   0   1   0   0   0
15   1   0   0   0   1   0   0   0   0   0   1   1   0   0   0
16   1   0   0   1   0   0   0   1   0   0   0   0   1   0   0
17   1   0   0   0   0   1   0   0   0   1   0   0   0   1   0
18   1   0   0   0   1   0   0   0   0   0   1   0   0   1   1
19   1   0   0   0   0   1   0   0   0   1   0   0   1   0   0
20   1   0   0   1   0   0   0   0   0   0   1   0   1   0   1
21   1   0   0   0   1   0   0   0   0   0   1   0   1   0   0
22   1   0   0   0   0   0   1   0   0   1   0   0   0   1   0
23   1   0   0   1   0   0   0   0   0   1   0   0   0   1   0
24   0   1   0   0   0   0   1   1   0   0   0   0   0   1   0
25   0   1   0   0   1   0   0   1   0   0   0   0   1   0   1
26   0   1   0   0   0   1   0   1   0   0   0   0   1   0   1
27   0   1   0   0   1   0   0   0   0   0   1   1   0   0   1
28   0   1   0   1   0   0   0   0   0   1   0   0   0   1   0
29   0   1   0   0   0   1   0   0   0   0   1   1   0   0   1
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
50   0   1   0   0   1   0   0   1   0   0   0   0   0   1   1
51   0   1   0   0   0   0   1   0   0   0   1   0   0   1   0
52   0   1   0   0   0   1   0   0   0   0   1   0   1   0   1
53   0   1   0   0   1   0   0   0   1   0   0   1   0   0   1
54   0   1   0   1   0   0   0   1   0   0   0   1   0   0   1
55   0   0   1   0   0   0   1   1   0   0   0   0   1   0   1
56   0   0   1   0   1   0   0   0   1   0   0   0   1   0   1
57   0   0   1   0   0   1   0   0   1   0   0   0   0   1   1
58   0   0   1   0   0   1   0   1   0   0   0   0   0   1   1
59   0   0   1   0   0   1   0   0   0   1   0   0   0   1   0
60   0   0   1   0   1   0   0   1   0   0   0   0   0   1   0
61   0   0   1   0   1   0   0   0   0   1   0   1   0   0   1
62   0   0   1   0   0   1   0   0   1   0   0   1   0   0   1
63   0   0   1   0   1   0   0   1   0   0   0   1   0   0   1
64   0   0   1   0   0   0   1   0   0   0   1   0   1   0   0
65   0   0   1   0   0   0   1   0   1   0   0   0   1   0   1
66   0   0   1   0   1   0   0   0   0   0   1   0   1   0   0
67   0   0   1   0   0   0   1   1   0   0   0   1   0   0   0
68   0   0   1   0   1   0   0   0   1   0   0   0   0   1   0
69   0   0   1   0   0   0   1   0   1   0   0   1   0   0   0
70   0   0   1   1   0   0   0   0   0   1   0   0   0   1   0
71   0   0   1   0   0   0   1   0   0   0   1   0   0   1   1
72   0   0   1   1   0   0   0   0   0   1   0   1   0   0   0
73   0   0   1   1   0   0   0   0   0   0   1   1   0   0   0
74   0   0   1   0   0   0   1   0   0   1   0   0   1   0   0
75   0   0   1   0   1   0   0   0   0   1   0   0   1   0   0
76   0   0   1   0   1   0   0   1   0   0   0   0   1   0   1
77   0   0   1   1   0   0   0   1   0   0   0   1   0   0   0
78   0   0   1   1   0   0   0   0   0   0   1   0   1   0   1
79   0   0   1   1   0   0   0   1   0   0   0   0   0   1   0

[80 rows x 15 columns]

In [16]:
# generate populasi dulu dri data latih (train)
def generate_chromosome(n_population,n_gen):
    population = []
    for i in range (n_population):
        gen = rd.choices([0,1],k=n_gen) #1 gen
        population.append(np.array(gen))
    return population

In [17]:
# test generate chromsome
generate_chromosome(10,15)

[array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1]),
 array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0]),
 array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1]),
 array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1]),
 array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1])]

In [5]:
#suhu  3 bit ,waktu 4 bit,kondisi lngit 4, kelembab 3 bit terbang 1 bit
sliceDataset = [np.split(rule,[3,7,11,14])]
sliceChromsome = [np.split(rule,[3,7,11,14]
suhu = cekSuhu(sliceDataset[0],sliceChromosome[0])
waktu = cekWaktu(sliceDataset[1],sliceChromosome[1])
kondisiLangit = cekKondisiLangit(sliceDataset[2],sliceChromosome[2])
kelembapan = cekKelembapan(sliceDataset[3],sliceChromosome[3])

SyntaxError: invalid syntax (<ipython-input-5-b704d459c2cf>, line 4)

In [7]:
#mengecek semua fungsi cek, kalau true semua tinggal dibandingin sama
def perbandingan(bool):
    if cekSuhu(a,b) and cekKondisiLangit(a,b) and cekKelembapan(a,b) and cekWaktu(a,b) == True:
        return True
    

In [ ]:
#fungsi cek suhu
def cekSuhu(a,b):
    return np.any(np.logical_and(a,b))

In [ ]:
#fungsi cek waktu
def cekWaktu(a,b)
    return np.any(np.logical_and(a,b))

In [ ]:
#fungsi cek kondisi langit
def cekKondisiLangit(a,b):
    return np.any(np.logical_and(a,b))    

In [4]:
#fungsi cek kelembapan
def cekKelembapan(a,b):
    return np.any(np.logical_and(a,b))

In [3]:
#perbandingan hasil perbandingan 4 feature dgn fitur terbang ya/tidak
def perbandinganFinal(bool):
    if perbandingan(bool) and (if rule[14] == row[14] ):
        return True

SyntaxError: invalid syntax (<ipython-input-3-263a55375b5b>, line 3)

In [2]:
#hitung fitness
def calc_fitness(datrain,population):
    fitness = []
    for chrom in population:
        split #tiap kromsom bisa berisi lebih dri 1 rule
        i = 0
        for data in datrain:
            if data == datrain:
                i+=1
                fitness += i
        fitness.append(i/80*100)
    return fitness
            

In [ ]:
#fungsi crossover
def crossOver(p1,p2):
    c1 = np.array(p1)
    c2 = np.array(p2)
    
    
    t1 = rd.ranrange(0, len(p1)+1)
    t2 = rd.randrange(0, len(p2)+1)
    if (t1>t2):
        t1,t2 = t2,t1
    
    
    new1 = np.hstack([c2[:t2],c1,c2[t2:]])
    new2 = np.hstack([c2[:t2],c2,c1[t2:]])
    
    return new1.tolist(), new2tolist()
