In [4]:
#import libray yg dibutuhkan
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import random as rd

In [6]:
#import data ke sini dulu
data = pd.read_csv("datatrain.csv")
data.head()

Suhu  Waktu Kondisi Langit Kelembapan Terbang/Tidak
0  Normal  Siang        Berawan     Normal         Tidak
1  Normal  Siang          Cerah     Normal         Tidak
2  Normal   Pagi          Hujan     Normal         Tidak
3  Normal   Sore         Rintik     Rendah            Ya
4  Normal  Malam        Berawan     Tinggi         Tidak

In [7]:
#ubah data jadi biner
enc = OneHotEncoder(sparse=False)
datrain = enc.fit_transform(data).astype(int)
datrain = np.delete(datrain,14,1)
pd.DataFrame(datrain).head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   1   0   0   0   0   1   0   1   0   0   0   1   0   0   0
1   1   0   0   0   0   1   0   0   1   0   0   1   0   0   0
2   1   0   0   0   1   0   0   0   0   1   0   1   0   0   0
3   1   0   0   0   0   0   1   0   0   0   1   0   1   0   1
4   1   0   0   1   0   0   0   1   0   0   0   0   0   1   0

In [8]:
# generate populasi dulu dri data latih (train)
def generate_chromosome(n_population):
    population = []
    for i in range (n_population):
        n_kromsom = rd.randint(1,10)*15
        kromsom = rd.choices([0,1],k=n_kromsom) #1 gen
        population.append(np.array(kromsom))
    return population

In [9]:
# test generate chromsome
population = generate_chromosome(10)

In [10]:
def fitnessKromosom(kromsom,data_train):
    hitung = 0
    array_rule = np.split(kromsom,round(len(kromsom)/15))
    for data in data_train:
        kategoriData = np.split(data, [3,7,11,14])
        for rule in array_rule:
            kategoriRule = np.split(rule, [3,7,11,14])
            for i in range(5):
                if np.any(np.logical_and(kategoriData[i],kategoriRule[i]))==False:
                    break
            if i == 4:
                if(kategoriData[4] == kategoriRule[4]):
                    hitung += 1
                    break
    return hitung/80*100

In [11]:
def hitungfitness(populasi,data_train):
    fit = []
    for kromosom in populasi:
        fit.append(fitnessKromosom(kromosom,data_train))
    return fit

In [12]:
populasi = generate_chromosome(10)
fitness = hitungfitness(populasi,datrain)

In [13]:
populasi,fitness

([array([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
         0, 1, 0, 1, 1, 1, 0, 1]),
  array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
         0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
         1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
         0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
         0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
         1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
         0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
         0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,


In [ ]:
kromsom = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0])
fitnessKromosom(kromsom,datrain)

In [15]:
#seleksi ortu (turnamen selection)
def tournamentselection(populasi,fit):
    parent = []
    kandidat = rd.sample(list(zip(populasi,fit)),rd.randint(1,len(populasi)))
    kandidat = sorted(kandidat,key= lambda k:k[1],reverse=True)
    return kandidat[0][0]

In [16]:
tournamentselection(populasi,fitness)

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0])

In [17]:
#crossover 
def crossover(parent1,parent2):
    p1 = rd.randint(0,len(parent1))
    p2 = rd.randint(0,len(parent1))
    if p1 > p2:
        p1,p2 = p2,p1
    pp1 = p2 - p1     
    gap = pp1 % 15    
    kondisi1 = []
    kondisi1.append(p1)
    kondisi1.append(p1+pp1)
    
    kondisi2 = []
    kondisi2.append(p1)
    kondisi2.append(p1+gap)
    
    kondisi3 = []
    kondisi3.append(abs(pp1-p2))
    kondisi3.append(p2)
    
    kondisi4 = []
    kondisi4.append(abs(gap-p2))
    kondisi4.append(p2)
    
    pp2 = []
    pp2.append(kondisi1)
    pp2.append(kondisi2)
    pp2.append(kondisi3)
    pp2.append(kondisi4)
    
    variabelrandomP2 = rd.randint(0,3)
    
    temp1 = []
    if p1 < p2:
        for i in range(p1,p2):
            temp1.append(parent1[p1])
    elif p2 < p1:
        for i in range(p2,p1):
            temp1.append(parent1[p2])
            
    varianTerpilih = pp2[variabelrandomP2]
    
    if varianTerpilih[1]>len(parent2):
        p3 = rd.randint(0,len(parent2)-gap)
        kondisi5 = []
        kondisi5.append(p3)
        kondisi5.append(p3+gap)
        varianTerpilih = kondisi5
        
    temp2 = []
    if varianTerpilih[0] < varianTerpilih[1]:
        for i in range(varianTerpilih[0],varianTerpilih[1]):
            temp2.append(parent2[i])
    elif varianTerpilih[1] < varianTerpilih[0]:
        for i in range (varianTerpilih[1],varianTerpilih[0]):
            temp2.append(parent2[i])
            
    
    
    #crossover
    prob = 1
    if prob >= np.random.uniform(0,1):
        parent1 = np.delete(parent1, range(p1,p2))
        parent1 = np.insert(parent1,p1,temp2)
        parent2 = np.delete(parent2,range(varianTerpilih[0],varianTerpilih[1]))
        parent2 = np.insert(parent2, varianTerpilih[0],temp1)
        
    return parent1, parent2

In [18]:
#test crossover
a = np.zeros(45)
b = np.arange(0,15)
a,b = crossover(a,b)
print(a,b,sep='\n')
len(a),len(b)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  4.  5.
  6.  7.  8.  9. 10. 11. 12. 13. 14.  0.  0.  0.]
[0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


(30, 30)

In [22]:
#mutasi
def mutasi(kromsom, prbmutasi):
    for i in range(len(kromsom)):
        if prbmutasi >= np.random.uniform(0,1):
            ambilNilai = rd.randint(0,1)
            kromsom[i] = ambilNilai
    return kromsom
        

In [23]:
prbmutasi = 0.1
mutasi(kromsom,prbmutasi)

NameError: name 'kromsom' is not defined

In [24]:
def elitisme(populasi,fitness):
    temp = zip(populasi,fitness)
    temp = sorted(temp,key= lambda k:k[1],reverse=True)
    return [temp[0][0],temp[1][0]]

In [25]:
elitisme(populasi,fitness)

[array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1])]

In [284]:
def prediksi(kromsom,data_uji):
    prdk = False
    array_rule = np.split(kromsom,round(len(kromsom)/15))
    for data in data_uji:
        kategoriData = np.split(data, [3,7,11,14])
        for rule in array_rule:
            kategoriRule = np.split(rule, [3,7,11,14])
            for i in range(5):
                if np.any(np.logical_and(kategoriData[i],kategoriRule[i]))==False:
                    break
            if i == 4:
                prdk = np.logical_or(kategoriData[u],kategoriRule[i])# mengeck terakhir
                break
    return prdk

In [241]:
data = pd.read_csv('data_latih_opsi_2.csv',header=None,names=['Suhu','Waktu','Kondisi_Langit','Kelembapan','Terbang/Tidak']) ## Baca dataset

In [240]:
A,B = data.drop(['Terbang/Tidak'],axis=1),data['Terbang/Tidak'] 

In [ ]:
def main(A, B, generasi,n_population):
    populasi = generate_chromosome(n_population)
    fitness = hitungfitness(populasi,datrain)
    populasi.sort(key= lambda k:k[1],reverse=True)  
    for i in range(generasi): 
        new_pop = elitisme(populasi,fitness) 
        for j in range(n_population//2): 
            parent1 = tournamentselection(populasi,fitness)
            parent2 = tournamentselection(populasi,fitness)
            anak = crossover(parent1,parent2) 
            new_pop.extend(anak)        
        for j in range(1,len(new_pop)): 
            mutasi(new_pop[j],prbmutasi) 
            hitungfitness(new_pop,datrain) 
        populasi = new_pop 
        populasi.sort(key= lambda k:k[1],reverse=True) 
    return populasi[0] 

In [281]:
z = main(A,B,20,20)

In [349]:
#prediks
data_uji = pd.read_csv('data_uji_opsi_2.csv',header=None,names=['Suhu','Waktu','Kondisi_Langit','Kelembapan','Terbang/Tidak'])
dat_uji = data_uji.drop(['Terbang/Tidak'],axis=1)
prdk = prediksi(z,dat_uji)
prdk.astype(int)
np.savetxt('HasilUji.txt',prdk,fmt='%.0d')