In [ ]:
#import libray yg dibutuhkan
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import random as rd

In [ ]:
#import data ke sini dulu
data = pd.read_csv("datatrain.csv")
data.head()

In [ ]:
#ubah data jadi biner
enc = OneHotEncoder(sparse=False)
datrain = enc.fit_transform(data).astype(int)
datrain = np.delete(datrain,14,1)
pd.DataFrame(datrain)

In [93]:
# generate populasi dulu dri data latih (train)
def generate_chromosome(n_population):
    population = []
    for i in range (n_population):
        n_kromsom = rd.randint(1,10)*15
        kromsom = rd.choices([0,1],k=n_kromsom) #1 gen
        population.append(np.array(kromsom))
    return population

In [84]:
# test generate chromsome
generate_chromosome(10)

[array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0]),
 array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 0]),
 array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 1]),
 array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,

In [ ]:
suhu = ["rendah","normal","tinggi"]
waktu = ["pagi","siang","sore","malam"]
langit = ["hujan","rintik","berawan","cerah"]
langit = ["rendah","normal","tinggi"] 
kelembaban = ["rendah","normal","tinggi"]
terbang = ["ya"]

In [ ]:
def checkChromosome(column, feature, value):
    i = column.index(value)
    return rule[i] == 1

In [ ]:
def checkFeature(kromsom, data):
    chromosomeFeature = featureChromosome(n_kromsom)
    for divChromosome in chromosomeFeature :
        sliceChromsome = [np.split(rule,[3,7,11,14]
        
        if checkChromosome(suhu,)

In [60]:
a = rd.choices([0,1],k=15)
b = rd.choices([0,1],k=15)
fitur_a = np.split(a , [3,7,11,14])
fitur_b = np.split(b , [3,7,11,14])
for i in range(4):
    print(fitur_a[i],'==',fitur_b[i])
    print(np.any(np.logical_and(fitur_a[i],fitur_b[i])))

[1 1 0] == [0 1 1]
True
[0 1 0 1] == [0 0 1 1]
True
[1 0 0 0] == [0 1 1 1]
False
[0 0 0] == [0 0 0]
False


In [75]:
chrom = np.array(rd.choices([0,1],k=45))
np.split(chrom,round(len(chrom)/15))

[array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0])]

In [102]:
def bagiKromsom(kromsom,data):
    krom = np.split(kromsom,round(len(kromsom)/15))
    sliceData = np.split(data , [3,7,11,14])
    sliceKromsom = np.split(kromsom, [3,7,11,14])
    for i in range (4):
        print(np.any(np.logical_and(data[i], kromsom[i])))


In [98]:
chrom = np.array(rd.choices([0,1],k=45))
bagiKromsom(chrom, datrain)

False
False
False
True


In [ ]:
#np.any(np.logical_and(a,b))
#fiturkromsom
def featureChromosome(n_gen):
    return [n_gen[i:i + 15] for i in range(0, len(kromsom),15)]