In [6]:
import random as rd
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [7]:
data = pd.read_csv("dataset.csv")
data.head()

Suhu  Waktu Kondisi Langit Kelembapan Terbang/Tidak
0  Normal  Siang        Berawan     Normal         Tidak
1  Normal  Siang          Cerah     Normal         Tidak
2  Normal   Pagi          Hujan     Normal         Tidak
3  Normal   Sore         Rintik     Rendah            Ya
4  Normal  Malam        Berawan     Tinggi         Tidak

In [8]:
enc = OneHotEncoder(sparse=False)
train = enc.fit_transform(data).astype(int)
train = np.delete(train,14,1)
pd.DataFrame(train).head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   1   0   0   0   0   1   0   1   0   0   0   1   0   0   0
1   1   0   0   0   0   1   0   0   1   0   0   1   0   0   0
2   1   0   0   0   1   0   0   0   0   1   0   1   0   0   0
3   1   0   0   0   0   0   1   0   0   0   1   0   1   0   1
4   1   0   0   1   0   0   0   1   0   0   0   0   0   1   0

In [9]:
def generate_chromosome(n_population,n_gen):
    population = []
    for i in range(n_population):
        gen = rd.choices([0,1],k=n_gen) # 1 gen
        population.append(np.array(gen))
    return population

In [11]:
generate_chromosome(10,15)

[array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1])]

In [12]:
a = [1,0,0]
b = [1,0,1]
np.any(np.logical_and(a,b))

True

In [13]:
arr = np.arange(0,45)
rules = np.split(arr,round(len(arr)/15))
rules
features = []
for rule in rules:
    features.append(np.split(rule,[3,7,11,14]))
features

[[array([0, 1, 2]),
  array([3, 4, 5, 6]),
  array([ 7,  8,  9, 10]),
  array([11, 12, 13]),
  array([14])],
 [array([15, 16, 17]),
  array([18, 19, 20, 21]),
  array([22, 23, 24, 25]),
  array([26, 27, 28]),
  array([29])],
 [array([30, 31, 32]),
  array([33, 34, 35, 36]),
  array([37, 38, 39, 40]),
  array([41, 42, 43]),
  array([44])]]

In [14]:
def calc_fitness(data_train,population):
    fitness = []
    for chrom in population:
        split # each chromosome can contain more than 1 rule
        i = 0
        for data in data_train:
            cocokin
            if sama :
                i+=1
            hjabskdbjasd
        fitness.append(i/80*100)
    return fitness

In [3]:
def crossOver(p1, p2):
    c1 = np.array(p1)
    c2 = np.array(p2)
    
    # If both length are 15
    if (len(c1) == 15 and len(c2) == 15):
        t1 = rd.randrange(0, len(p1)+1)
        t2 = rd.randrange(0, len(p2)+1)
        if (t1>t2):
            t1, t2 = t2, t1
        
        new1 = np.hstack([c2[:t2], c1, c2[t2:]])
        new2 = np.hstack([c1[:t2], c2, c1[t2:]])
        
        return new1.tolist(), new2.tolist()
    else:
#         print("INI")
        t1 = rd.randrange(0, len(c1))
        t2 = rd.randrange(0, len(c1))
        
        temp1 = c1.copy()
        temp2 = c2.copy()
        
        gen = 0
        gap = 0
        # To avoid gap = gen
        while (gen == gap):
            t1 = rd.randrange(0, len(c1))
            t2 = rd.randrange(0, len(c1))
            if (t1>t2):
                t1, t2 = t2, t1
                
            gen = t2 - t1
            gap = gen % 15
        
        # List of the possible index
        list_idx = [[t1,t1+gap], [t1,t1+gen], [t2-gap, t2]]
#         print("LIST",list_idx)
        
        t3 = rd.randrange(0, len(c1))
        idx3 = 0
        if (t3-gap < 0):
            idx3 = t3 + gap
        else:
            idx3 = t3 - gap
        
        if (t3 > idx3):
            t3, idx3 = idx3, t3
#         print("KE 3 ",t3, idx3)
        # Choose the point to crossover
        idx = rd.choice(list_idx)
        
        x1, y1 = temp1[:idx[0]], temp1[idx[1]+1:]
        x2, y2 = temp2[:t3], temp2[idx3+1:]
        
        new1 = np.hstack([x1, temp2[t3:idx3+1], y1])
        new2 = np.hstack([x2, temp1[idx[0]:idx[1]+1], y2])

        return new1.tolist(), new2.tolist()

In [15]:
p1 = np.arange(0,30).tolist()
p2 = np.zeros(30).tolist()
a,b = crossOver(p1,p2)
print(*crossOver(p1,p2),sep='\n')
len(a),len(b)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 0.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


(30, 30)